# Question 3: Exam Score Analysis (NumPy)

## 1. Matrix Creation

In [18]:
import numpy as np

exam_scores = np.array([
    [85, 92, 78, 90],
    [76, 88, 92, 80],
    [90, 85, 88, 95],
    [82, 78, 88, 75],
    [88, 90, 85, 92]]
)

exam_scores

array([[85, 92, 78, 90],
       [76, 88, 92, 80],
       [90, 85, 88, 95],
       [82, 78, 88, 75],
       [88, 90, 85, 92]])

#### b. Key Differeence between Python List and Numpy Array:
A Python list can store elements of different data types and is slower for numerical operations. A NumPy array stores elements of the same data type and is optimized for fast mathematical and numerical computations.

## 2. Statistical Analysis

In [19]:
max_score = np.max(exam_scores, axis=0)
min_score = np.min(exam_scores, axis=0)

print("Maximum score per subject: ", max_scores)
print("Minimum score per subject: ", min_score)

Maximum score per subject:  [90 88 92 94]
Minimum score per subject:  [76 78 78 75]


In [20]:
class_average = np.mean(exam_scores)
print("Average score of the entire class: ", class_average)

Average score of the entire class:  85.85


## 3. Advanced Analysis

#### Find Student (Row Index) who had the highest total score

In [21]:
total_scores_per_student = np.sum(exam_scores, axis=1)

print(total_scores_per_student)

top_student_idx = np.argmax(total_scores_per_student)

print("Student with highest total score (row index): ", top_student_idx)

[345 336 358 323 355]
Student with highest total score (row index):  2


#### Find the Subject (Column Index) that had the lowest average score

In [22]:
average_score_per_subject = np.mean(exam_scores, axis=0)

print(average_score_per_subject)

lowest_subject_idx = np.argmin(average_score_per_subject)

print("Subject with lowest average score (column index): ", lowest_subject_idx)

[84.2 86.6 86.2 86.4]
Subject with lowest average score (column index):  0
